services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks: 
      - app-network
  
  frontend:
    build:
      context: ./frontend/vue-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://localhost:8000

networks:
  app-network:
    driver: bridge
