version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend/angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://localhost:8080
    
  backend:
    build:
      context: ./backend/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge