services:
  frontend:
    image: frontend
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000